channel:
  I2I:
    fastfading_model: Rayleigh
    pathloss_model: free_space
    shadowing_model: 3GPP_LogNormal
  U2I:
    fastfading_model: Rayleigh
    pathloss_model: free_space
    shadowing_model: 3GPP_LogNormal
  U2U:
    fastfading_model: Rayleigh
    pathloss_model: free_space
    shadowing_model: 3GPP_LogNormal
  V2I:
    fastfading_model: Rayleigh
    pathloss_model: UMa_LOS_tr38901
    shadowing_model: 3GPP_LogNormal
  V2U:
    fastfading_model: Rayleigh
    pathloss_model: free_space
    shadowing_model: 3GPP_LogNormal
  V2V:
    fastfading_model: Rayleigh
    pathloss_model: V2V_urban_tr37885
    shadowing_model: 3GPP_LogNormal
  outage_model: Rayleigh
  outage_snr_threshold: 10
energy:
  fly_unit_cost: 2.5
  hover_unit_cost: 1.2
  initial_energy_range:
  - 48000
  - 52000
  receive_unit_cost: 0.1
  send_unit_cost: 0.1
  sensing_unit_cost: 0.5
fog_profile:
  cloud:
    cpu: 20.0
    memory: 1
    storage: 1
  rsu:
    cpu: 5.0
    memory: 1
    storage: 1
  uav:
    cpu: 2.0
    memory: 1
    storage: 1
  vehicle:
    cpu: 1.0
    memory: 1
    storage: 1
mission:
  TTL_range:
  - 100
  - 200
  UAV_height: 100
  distance_threshold: 150
  duration_range:
  - 5
  - 10
  generation_model_args:
    Exponential:
      beta: 1
    Normal:
      mean: 0
      std: 1
    Poisson:
      lambda: 1
    Uniform:
      high: 1
      low: 0
  mission_generation_model: Poisson
  mission_size_range:
  - 10
  - 20
  predictable_seconds: 2
  sensor_accuracy_range:
  - 0
  - 1
sensing:
  node_type:
  - UAV
  - vehicle
  sensor_type_num: 4
  sensors_per_node: 4
simulation:
  max_simulation_time: 100.0
  simulation_interval: 0.1
  traffic_interval: 0.1
  vehicle_count: 50
state_attribute:
  fog_node_state_attributes:
  - position_x
  - position_y
  - position_z
  - speed
  - fog_profile
  - node_type
  log_state: false
  task_node_state_attributes:
  - position_x
  - position_y
  - position_z
  - speed
  - task_profile
  - node_type
  task_state_attributes:
  - task_node_id
  - task_size
  - task_cpu
  - required_returned_size
  - task_deadline
  - task_priority
  - task_arrival_time
  - task_lifecycle_state
  time_window: 3
sumo:
  export_tripinfo: false
  sumo_config: ./sumo_wujiaochang/osm.sumocfg
  sumo_net: ./sumo_wujiaochang/osm.net.xml
  sumo_osm: ./sumo_wujiaochang/osm_bbox.osm.xml
  sumo_port: 8813
  tripinfo_output: ./sumo_wujiaochang/tripinfo.xml
task:
  cpu_kwargs:
    high: 0.7
    low: 0.7
  cpu_model: Uniform
  deadline_kwargs:
    high: 1
    low: 1
  deadline_model: Uniform
  hard_ddl: 2
  priority_kwargs:
    high: 1
    low: 1
  priority_model: Uniform
  required_returned_size_kwargs:
    high: 0
    low: 0
  required_returned_size_model: Uniform
  size_kwargs:
    high: 0.7
    low: 0.7
  size_model: Uniform
  task_generation_kwargs:
    lambda: 0.1
  task_generation_model: Poisson
  task_max_cpu: 1.5
  task_max_deadline: 2
  task_max_priority: 1
  task_max_required_returned_size: 0
  task_max_size: 1.5
  task_min_cpu: 1.5
  task_min_deadline: 2
  task_min_priority: 1
  task_min_required_returned_size: 0
  task_min_size: 1.5
  tti_threshold: 0.5
task_profile:
  task_node_gen_poss: 0.5
  task_node_profiles:
  - max_node_num: 30
    type: UAV
  - max_node_num: 20
    type: vehicle
  uav:
    dag_edge_prob: 0.3
    lambda: 0.1
  vehicle:
    dag_edge_prob: 0.3
    lambda: 0.1
traffic:
  RSU_positions:
  - - 100
    - 100
    - 0
  - - 100
    - 2000
    - 0
  - - 2500
    - 100
    - 0
  - - 2500
    - 2000
    - 0
  UAV_speed_range:
  - 10
  - 30
  UAV_z_range:
  - 100
  - 200
  arrival_lambda: 1
  distance_threshold: 50
  max_n_UAVs: 10
  max_n_cloudServers: 1
  max_n_vehicles: 100
  nonfly_zone_coordinates:
  - - - 1000
      - 1200
    - - 1200
      - 1200
    - - 1200
      - 1000
    - - 1000
      - 1000
  - - - 1500
      - 1700
    - - 1700
      - 1700
    - - 1700
      - 1500
    - - 1500
      - 1500
  traffic_interval: 0.1
  traffic_mode: SUMO
  tripinfo: ./sumo_wujiaochang/tripinfo.csv
  uav_traffic_file: path/to/uav_traffic_file.csv
visualization:
  icon_path: ./icon
